#!/bin/bash

#SBATCH --job-name=ADHD200_batch13
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8GB
#SBATCH --time=13:00:00 #change time
#SBATCH --partition=cores
#SBATCH --mail-type=END,FAIL

module load Anaconda3
source activate thesis_env
    
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010021 0010022 0010023] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010028 0010030 0010038] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010034 0010031 0010032] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010035 0010037 0010039] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml