#!/bin/bash

#SBATCH --job-name=ADHD200_batch18
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8GB
#SBATCH --time=13:00:00 #change time
#SBATCH --partition=cores
#SBATCH --mail-type=END,FAIL

module load Anaconda3
source activate thesis_env
    
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010098 0010099 0010100] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010101 0010102 0010108] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010002 0010011 0010113] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [0010114 0010115 0010006] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml