#!/bin/bash

#SBATCH --job-name=ADHD200_batch10
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8GB
#SBATCH --time=13:00:00 #change time
#SBATCH --partition=cores
#SBATCH --mail-type=END,FAIL

module load Anaconda3
source activate thesis_env
    
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [3845761 3999344 4060823] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [4079254 4084645 4095229] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [4116166 4154672 4164316] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU /home/mrla/Thesis/data/preprocessed/ADHD200 participant --participant-label [4187857 4562206 4827048] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml