#!/bin/bash

#SBATCH --job-name=ABIDEII_batch6
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8GB
#SBATCH --time=10:00:00 #change time
#SBATCH --partition=cores
#SBATCH --mail-type=END,FAIL

module load Anaconda3
source activate thesis_env
    
cpac run s3://fcp-indi/data/Projects/ABIDE2/RawData/ABIDEII-NYU_1 /home/mrla/Thesis/data/preprocessed/ABIDEII participant --participant-label [29222 29223 29224] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ABIDE2/RawData/ABIDEII-NYU_1 /home/mrla/Thesis/data/preprocessed/ABIDEII participant --participant-label [29225 29226 29227] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml
cpac run s3://fcp-indi/data/Projects/ABIDE2/RawData/ABIDEII-NYU_1 /home/mrla/Thesis/data/preprocessed/ABIDEII participant --participant-label [29228 29229 29230] --n_cpus 2 --mem_gb 16 --platform singularity --pipeline-file /home/mrla/Thesis/scripts/default_pipeline_changed_test.yml